namespace LibraryManagement.Application.Books.DTOs;

public class BookDto
{
    public Guid Id { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? ISBN { get; set; }
    public string? Description { get; set; }
    public string? CoverImageUrl { get; set; }
    public int TotalCopies { get; set; }
    public int AvailableCopies { get; set; }
    public bool IsAvailable { get; set; }
    public DateTime? PublishedDate { get; set; }
    public string? Publisher { get; set; }
    public int? PageCount { get; set; }
    public string? Language { get; set; }
    public Guid AuthorId { get; set; }
    public string AuthorName { get; set; } = string.Empty;
    public List<string> Categories { get; set; } = [];
    public DateTime CreatedAt { get; set; }
}

public class AuthorDto
{
    public Guid Id { get; set; }
    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
    public string? Biography { get; set; }
    public string FullName => $"{FirstName} {LastName}";
}

public class CategoryDto
{
    public Guid Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
}

public class CreateBookRequest
{
    public string Title { get; set; } = string.Empty;
    public string? ISBN { get; set; }
    public string? Description { get; set; }
    public string? CoverImageUrl { get; set; }
    public int TotalCopies { get; set; } = 1;
    public DateTime? PublishedDate { get; set; }
    public string? Publisher { get; set; }
    public int? PageCount { get; set; }
    public string? Language { get; set; }
    public Guid AuthorId { get; set; }
    public List<Guid>? CategoryIds { get; set; }
    public bool AutoGenerateDescription { get; set; }
}

public class UpdateBookRequest
{
    public string Title { get; set; } = string.Empty;
    public string? ISBN { get; set; }
    public string? Description { get; set; }
    public string? CoverImageUrl { get; set; }
    public int TotalCopies { get; set; }
    public DateTime? PublishedDate { get; set; }
    public string? Publisher { get; set; }
    public int? PageCount { get; set; }
    public string? Language { get; set; }
    public Guid AuthorId { get; set; }
    public List<Guid>? CategoryIds { get; set; }
}
