export interface Book {
  id: string;
  title: string;
  isbn: string | null;
  description: string | null;
  coverImageUrl: string | null;
  totalCopies: number;
  availableCopies: number;
  isAvailable: boolean;
  publishedDate: string | null;
  publisher: string | null;
  pageCount: number | null;
  language: string | null;
  authorId: string;
  authorName: string;
  categories: string[];
  createdAt: string;
}

export interface CreateBookRequest {
  title: string;
  isbn?: string;
  description?: string;
  coverImageUrl?: string;
  totalCopies: number;
  publishedDate?: string;
  publisher?: string;
  pageCount?: number;
  language?: string;
  authorId: string;
  categoryIds?: string[];
  autoGenerateDescription: boolean;
}

export interface UpdateBookRequest {
  title: string;
  isbn?: string;
  description?: string;
  coverImageUrl?: string;
  totalCopies: number;
  publishedDate?: string;
  publisher?: string;
  pageCount?: number;
  language?: string;
  authorId: string;
  categoryIds?: string[];
}

export interface Author {
  id: string;
  firstName: string;
  lastName: string;
  biography: string | null;
  fullName: string;
}

export interface Category {
  id: string;
  name: string;
  description: string | null;
}

export interface PagedResult<T> {
  items: T[];
  totalCount: number;
  pageNumber: number;
  pageSize: number;
  totalPages: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}

export interface QueryParameters {
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: string;
  searchTerm?: string;
  filters?: { [key: string]: string };
}
